import '../../../database/app_database.dart';

/// Anzeige-Namen für DeckArchetype - zentral gepflegt für Dropdown und
/// Deck-Anzeige. Bewusst durchgehend Englisch statt eines Mixes aus
/// deutschen Übersetzungen und englischen Fachbegriffen (Nutzerfeedback:
/// der Mix aus Deutsch/Englisch im Dropdown störte, Englisch ist in der
/// Magic-Community für diese Begriffe ohnehin gängig).
const Map<DeckArchetype, String> deckArchetypeLabels = {
  DeckArchetype.aggro: 'Aggro',
  DeckArchetype.midrange: 'Midrange',
  DeckArchetype.control: 'Control',
  DeckArchetype.combo: 'Combo',
  DeckArchetype.stax: 'Stax',
  DeckArchetype.voltron: 'Voltron',
  DeckArchetype.aristocrats: 'Aristocrats',
  DeckArchetype.spellslinger: 'Spellslinger',
  DeckArchetype.reanimator: 'Reanimator',
  DeckArchetype.tokens: 'Tokens',
  DeckArchetype.plusOneCounters: '+1/+1 Counters',
  DeckArchetype.lifegain: 'Lifegain',
  DeckArchetype.lifedrain: 'Lifedrain',
  DeckArchetype.ramp: 'Ramp',
  DeckArchetype.landfall: 'Landfall',
  DeckArchetype.landsMatter: 'Lands Matter',
  DeckArchetype.artifacts: 'Artifacts',
  DeckArchetype.enchantress: 'Enchantress',
  DeckArchetype.equipment: 'Equipment',
  DeckArchetype.vehicles: 'Vehicles',
  DeckArchetype.graveyard: 'Graveyard',
  DeckArchetype.selfMill: 'Self-Mill',
  DeckArchetype.mill: 'Mill',
  DeckArchetype.groupHug: 'Group Hug',
  DeckArchetype.groupSlug: 'Group Slug',
  DeckArchetype.pillowFort: 'Pillow Fort',
  DeckArchetype.politics: 'Politics',
  DeckArchetype.storm: 'Storm',
  DeckArchetype.wheels: 'Wheels',
  DeckArchetype.cardDraw: 'Card Draw',
  DeckArchetype.discard: 'Discard',
  DeckArchetype.blink: 'Blink',
  DeckArchetype.sacrifice: 'Sacrifice',
  DeckArchetype.theft: 'Theft',
  DeckArchetype.bigMana: 'Big Mana',
  DeckArchetype.goodStuff: 'Good Stuff',
  DeckArchetype.superfriends: 'Superfriends',
  DeckArchetype.tribal: 'Tribal',
  DeckArchetype.infect: 'Infect',
  DeckArchetype.extraCombats: 'Extra Combats',
  DeckArchetype.burn: 'Burn',
  DeckArchetype.tempo: 'Tempo',
  DeckArchetype.hatebears: 'Hatebears',
  DeckArchetype.toolbox: 'Toolbox',
  DeckArchetype.monarch: 'Monarch',
  DeckArchetype.treasure: 'Treasure',
  DeckArchetype.food: 'Food',
  DeckArchetype.devotion: 'Devotion',
  DeckArchetype.prowess: 'Prowess',
  DeckArchetype.cedh: 'cEDH',
};
